#!/bin/sh
#
# Apply the iptables rules
#

case "$1" in
  start)
        iptables-restore /etc/iptables.conf
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
