#!/bin/sh
#
# Set the time
#

case "$1" in
  start)
        printf "Syncing time with time.google.com: "
        ntpdate time.google.com
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
