#!/bin/sh
#
# Start crond
#

case "$1" in
  start)
	mkdir -p /var/spool/cron/crontabs
	touch /var/spool/cron/crontabs/root
	crond
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
